version: '3'

services:

  activemq:
    restart: unless-stopped
    image: seniocaires/activemq:5.15.8
    ports:
      - "61616:61616"
      - "8161:8161"

  webscraper_regiao:
    restart: unless-stopped
    links:
      - activemq:broker
    build:
      context: ./olx-webscraper
    image: seniocaires/olx_webscraper
    environment:
      - UF=mg
      - BROKER_URL=tcp://broker:61616?jms.prefetchPolicy.all=1
      - BROKER_USUARIO=
      - BROKER_SENHA=
      - SLEEP_MILISEGUNDOS=300000
    entrypoint: regiao

  webscraper_subregiao:
    restart: unless-stopped
    links:
      - activemq:broker
    image: seniocaires/olx_webscraper
    environment:
      - BROKER_URL=tcp://broker:61616?jms.prefetchPolicy.all=1
      - BROKER_USUARIO=
      - BROKER_SENHA=
      - TIMEOUT_PROCESSAMENTO_SEGUNDOS=30
    entrypoint: subregiao

  categoria:
    restart: unless-stopped
    links:
      - activemq:broker
    image: seniocaires/olx_webscraper
    environment:
      - BROKER_URL=tcp://broker:61616?jms.prefetchPolicy.all=1
      - BROKER_USUARIO=
      - BROKER_SENHA=
      - TIMEOUT_PROCESSAMENTO_SEGUNDOS=30
    entrypoint: categoria

  webscraper_subcategoria:
    restart: unless-stopped
    links:
      - activemq:broker
    image: seniocaires/olx_webscraper
    environment:
      - BROKER_URL=tcp://broker:61616?jms.prefetchPolicy.all=1
      - BROKER_USUARIO=
      - BROKER_SENHA=
      - TIMEOUT_PROCESSAMENTO_SEGUNDOS=30
    entrypoint: subcategoria

  webscraper_anuncio:
    restart: unless-stopped
    links:
      - activemq:broker
    image: seniocaires/olx_webscraper
    environment:
      - BROKER_URL=tcp://broker:61616?jms.prefetchPolicy.all=1
      - BROKER_USUARIO=
      - BROKER_SENHA=
      - TIMEOUT_PROCESSAMENTO_SEGUNDOS=300
    entrypoint: anuncio

